'use strict';
const $=id=>document.getElementById(id);
const PROVIDERS=['Shopify','Etsy','Amazon','Michaels','Faire'];
const COLORS={Shopify:'#8abd4c',Etsy:'#e98952',Amazon:'#efb049',Michaels:'#d95a72',Faire:'#8770d9'};
const ICONS={Shopify:'S',Etsy:'E',Amazon:'a',Michaels:'M',Faire:'F'};
const state={csrf:'',user:null,connections:[],configured:{},report:null,costs:[],fx:{},view:'overview',authMode:'login'};
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function money(value,currency){if(value===null||value===undefined)return '—';let n=Number(value);return new Intl.NumberFormat('en',{style:'currency',currency:currency||state.user?.currency||'EUR',maximumFractionDigits:2}).format(n)}
function compact(value){return new Intl.NumberFormat('en',{maximumFractionDigits:0}).format(Number(value)||0)}
function number(value){return new Intl.NumberFormat('en',{maximumFractionDigits:2}).format(Number(value)||0)}
function chip(name){return `<span class="channel-pill"><i style="background:${COLORS[name]||'#718096'}"></i>${esc(name)}</span>`}
async function api(url,opts={}){
 const options={credentials:'same-origin',...opts,headers:{...(opts.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(opts.headers||{})}};
 if(!['GET','HEAD'].includes((options.method||'GET').toUpperCase())&&state.csrf) options.headers['X-CSRF-Token']=state.csrf;
 let response=await fetch(url,options);let type=response.headers.get('content-type')||'';
 let data=type.includes('json')?await response.json():await response.text();
 if(!response.ok)throw new Error(typeof data==='object'?(data.detail||JSON.stringify(data)):`Request failed: ${response.status}`);
 return data;
}
function toast(text,isError=false){let t=$('toast');t.textContent=text;t.style.background=isError?'#a83d56':'#203353';t.hidden=false;clearTimeout(toast.timeout);toast.timeout=setTimeout(()=>t.hidden=true,6200)}
function authMode(mode){state.authMode=mode;const signup=mode==='register';$('authTitle').textContent=signup?'Create your workspace':'Welcome back';$('authSub').textContent=signup?'Everything your brand sells, in one place.':'Sign in to your sales workspace.';$('businessField').hidden=!signup;$('businessName').required=signup;$('authSubmit').innerHTML=signup?'Create account <span>→</span>':'Sign in <span>→</span>';$('authSwitchPrefix').textContent=signup?'Already have an account?':'New to ChannelPilot?';$('authSwitch').textContent=signup?'Sign in':'Create an account';$('password').autocomplete=signup?'new-password':'current-password';$('authError').hidden=true}
$('authSwitch').onclick=()=>authMode(state.authMode==='login'?'register':'login');
$('authForm').onsubmit=async e=>{e.preventDefault();$('authSubmit').disabled=true;$('authError').hidden=true;
 try{let out=await api('/api/auth/'+state.authMode,{method:'POST',body:JSON.stringify({email:$('email').value,password:$('password').value,business_name:$('businessName').value})});state.csrf=out.csrf;state.user=out.user;await enter()}
 catch(err){$('authError').textContent=err.message;$('authError').hidden=false}
 finally{$('authSubmit').disabled=false}
};
async function enter(){
 $('auth').hidden=true;$('app').hidden=false;$('businessLabel').textContent=state.user.business_name;$('businessInitial').textContent=state.user.business_name[0].toUpperCase();$('userInitial').textContent=state.user.email[0].toUpperCase();$('userEmail').textContent=state.user.email;
 await Promise.all([loadConnections(),loadCosts(),loadSettings(),loadReport()]);
 if(location.search.includes('connected=')){toast('Platform connected. Choose Sync now to import sales.');history.replaceState({},'',location.pathname)}
 navigate('overview');
}
async function boot(){try{let me=await api('/api/me');state.csrf=me.csrf;state.user=me.user;await enter()}catch(err){$('auth').hidden=false;$('app').hidden=true}}
async function loadConnections(){try{let obj=await api('/api/connections');state.connections=obj.connections;state.configured=obj.configured;$('connCount').textContent=state.connections.length;let synced=state.connections.map(c=>c.last_sync).filter(Boolean).sort().reverse()[0];$('updatedLabel').textContent=synced?'Synced '+new Date(synced).toLocaleDateString():'Awaiting first sync'}catch(err){toast('Could not load connections: '+err.message,true)}}
async function loadCosts(){try{state.costs=(await api('/api/costs')).costs}catch(err){toast(err.message,true)}}
async function loadSettings(){try{state.fx=await api('/api/settings')}catch(err){toast(err.message,true)}}
async function loadReport(){try{state.report=await api('/api/report?'+new URLSearchParams({period:$('period').value,sales_type:$('typeFilter').value,channel:$('channelFilter').value}));if(state.view!=='connections'&&state.view!=='settings'&&state.view!=='products')render()}catch(err){toast('Could not load sales: '+err.message,true)}}
function navigate(view){state.view=view;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const names={overview:['Overview','Good to see you','A single view of sales, products and profitability across every store.'],channels:['Sales channels','Where sales happen','Compare revenue and contribution across every connected channel.'],products:['Products & COGS','Know your margins','Shopify costs are matched by SKU to orders from every platform.'],orders:['Orders','Every order, in focus','One searchable record of sales across your business.'],connections:['Connections','Connect your channels','Link your store accounts to start consolidating sales automatically.'],settings:['Settings','Make the numbers yours','Choose your reporting currency and set exchange rates.']};let n=names[view];$('breadcrumb').textContent=n[0];$('pageTitle').innerHTML=esc(n[1])+'<span class="heading-dot">.</span>';$('pageSub').textContent=n[2];$('heroControls').hidden=['connections','settings'].includes(view);render()}
document.getElementById('nav').onclick=e=>{let btn=e.target.closest('[data-view]');if(btn)navigate(btn.dataset.view)};
document.querySelector('.sidebar .nav-label.second').nextElementSibling.onclick=e=>{let btn=e.target.closest('[data-view]');if(btn)navigate(btn.dataset.view)};
['period','typeFilter','channelFilter'].forEach(id=>$(id).onchange=loadReport);
$('syncAll').onclick=async()=>{$('syncAll').disabled=true;toast('Syncing connected stores…');try{let x=await api('/api/sync/all',{method:'POST'});let errors=x.results.filter(r=>r.error);await Promise.all([loadCosts(),loadConnections(),loadReport()]);toast(errors.length?`${x.results.length-errors.length} synced. ${errors.length} connector(s) need attention. See Connections.`:'Sales and product costs updated.');render()}catch(err){toast(err.message,true)}finally{$('syncAll').disabled=false}};
$('logout').onclick=async()=>{try{await api('/api/auth/logout',{method:'POST'})}catch(e){}window.location.assign('/')};
function empty(title,body,action=''){return `<div class="empty"><div class="empty-icon">◈</div><h3>${esc(title)}</h3><p>${esc(body)}</p>${action}</div>`}
function warningBar(){if(!state.report)return '';let w=state.report.warnings,s=state.report.summary;let parts=[];
 if(w.missing_fx.length)parts.push(`No exchange rate for ${esc(w.missing_fx.join(', '))}; ${w.fx_excluded_lines} line(s) excluded from totals.`);
 if(s.missing_cost_lines)parts.push(`${s.missing_cost_lines} of ${s.lines} lines lack complete costs. Profit excludes these lines.`);
 if(!parts.length)return '';
 return `<div class="banner"><span class="banner-icon">ⓘ</span><div><strong>Some figures need attention.</strong> ${parts.join(' ')} <button class="text-button" data-jump="settings">Review settings</button></div></div>`;
}
function stat(label,value,note,sym='↗',cls=''){return `<div class="stat-card"><div class="stat-label">${esc(label)}</div><div class="stat-symbol ${cls}">${sym}</div><div class="stat-number">${esc(value)}</div><div class="stat-note">${esc(note)}</div></div>`}
function cards(){let s=state.report?.summary;if(!s)return '';let c=state.report.currency;return `<div class="cards">${stat('Net sales',money(s.revenue,c),'After reported refunds · excludes tax','↗')}${stat('Orders',compact(s.orders),'Across selected sales channels','◷')}${stat('Gross profit',money(s.gross_profit,c),`${s.gross_profit_lines}/${s.lines} lines have Shopify COGS`,'◇','green')}${stat('Contribution profit',money(s.known_profit,c),`${s.complete_lines}/${s.lines} lines with all direct costs`,'◉','orange')}</div>`}
function chart(data){if(!data.length)return empty('A clear picture starts with data','Connect a channel or import your first sales export.');
 const nums=data.map(x=>Number(x.revenue));const max=Math.max(1,...nums);const W=680,H=230,left=52,right=15,top=18,bottom=30,w=W-left-right,h=H-top-bottom;
 let points=nums.map((v,i)=>[left+(data.length===1?w/2:i*w/(data.length-1)),top+h-v/max*h]);
 const line=points.map((p,i)=>(i?'L':'M')+p.join(' ')).join(' ');const fill=line+` L${points.at(-1)[0]} ${top+h} L${points[0][0]} ${top+h} Z`;
 let guides='';for(let i=0;i<4;i++){let y=top+i*h/3;guides+=`<line x1="${left}" x2="${W-right}" y1="${y}" y2="${y}" stroke="#edf0f5" stroke-dasharray="4 5"/><text x="${left-8}" y="${y+4}" text-anchor="end" class="axis-text">${compact(max*(1-i/3))}</text>`}
 let tickIds=[0,Math.floor((data.length-1)/2),data.length-1].filter((v,i,a)=>a.indexOf(v)===i);
 let labels=tickIds.map(i=>`<text x="${points[i][0]}" y="${H-4}" text-anchor="middle" class="axis-text">${new Date(data[i].date+'T12:00:00').toLocaleDateString('en',{month:'short',day:'numeric'})}</text>`).join('');
 return `<div class="chart"><svg role="img" aria-label="Daily sales trend" viewBox="0 0 ${W} ${H}" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#6677e8" stop-opacity=".18"/><stop offset="100%" stop-color="#6677e8" stop-opacity="0"/></linearGradient></defs>${guides}<path class="chart-fill" d="${fill}"/><path class="chart-line" d="${line}"/>${points.length<18?points.map(p=>`<circle class="chart-dot" cx="${p[0]}" cy="${p[1]}" r="4"/>`).join(''):''}${labels}</svg></div>`;
}
function breakdown(channels){if(!channels.length)return empty('No channel activity yet','Connect a store to compare its contribution.');let max=Math.max(...channels.map(x=>Number(x.revenue)),1);return `<div class="legend-list">${channels.map(ch=>`<div class="legend-item"><span class="dot" style="background:${COLORS[ch.channel]}"></span><span>${esc(ch.channel)}</span><span class="bar-bg"><span class="bar" style="display:block;width:${Math.max(2,Number(ch.revenue)/max*100)}%;background:${COLORS[ch.channel]}"></span></span><strong>${money(ch.revenue,state.report.currency)}</strong></div>`).join('')}</div><p class="small-note" style="margin:28px 0 0">Faire orders are classified as wholesale. Revenue across platforms is converted using your saved FX rates.</p>`}
function formatProfit(x,complete=true){return x===null||!complete?'<span class="missing">Costs missing</span>':`<span class="${Number(x)<0?'profit-neg':'profit-pos'}">${money(x,state.report.currency)}</span>`}
function productTable(products){if(!products.length)return empty('Your product ranking will appear here','Connect a selling platform or upload orders to find your best-selling SKUs.');return `<div class="table-wrap"><table><thead><tr><th>SKU</th><th>Product</th><th class="right">Units</th><th class="right">Net sales</th><th class="right">Gross profit</th><th class="right">Contribution</th><th class="right">Full costs</th></tr></thead><tbody>${products.map(p=>`<tr><td class="sku">${esc(p.sku)}</td><td>${esc(p.product||'—')}</td><td class="right">${number(p.units)}</td><td class="right">${money(p.revenue,state.report.currency)}</td><td class="right">${formatProfit(p.gross_profit,p.cogs_lines>0)}</td><td class="right">${formatProfit(p.profit,p.complete>0)}</td><td class="right">${p.complete}/${p.lines}</td></tr>`).join('')}</tbody></table></div>`}
function orderTable(rows){if(!rows.length)return empty('No orders in this view','Connect a platform or import an order export to get started.');return `<div class="table-wrap"><table><thead><tr><th>Order</th><th>Channel</th><th>Date</th><th>SKU</th><th class="right">Qty</th><th class="right">Net sales</th><th class="right">COGS</th><th class="right">Verified profit</th></tr></thead><tbody>${rows.map(r=>`<tr><td class="sku">${esc(r.order_id)}</td><td>${chip(r.provider)}</td><td>${esc(new Date(r.ordered_at).toLocaleDateString())}</td><td>${esc(r.sku||'—')}</td><td class="right">${number(r.quantity)}</td><td class="right">${money(r.revenue,state.report.currency)}</td><td class="right">${r.cogs===null?'<span class="missing">Unknown</span>':money(r.cogs,state.report.currency)}</td><td class="right">${formatProfit(r.profit)}</td></tr>`).join('')}</tbody></table></div>`}
function overview(){let r=state.report;if(!r)return empty('Loading your workspace','Retrieving sales data.');return `${warningBar()}${cards()}<div class="grid-two"><section class="panel"><div class="panel-head"><div><h2>Sales over time</h2><p>Your daily net sales in ${esc(r.currency)}</p></div><span class="tag">${r.period===3650?'All available':r.period+' days'}</span></div>${chart(r.trend)}</section><section class="panel"><div class="panel-head"><div><h2>Sales by channel</h2><p>How every store contributes</p></div><span class="tag">${r.channels.length} active</span></div>${breakdown(r.channels)}</section></div><section class="panel panel-spaced"><div class="table-head"><h2>Products worth watching</h2><button class="outline small" data-jump="products">All products →</button></div>${productTable(r.products.slice(0,6))}</section><section class="panel panel-spaced"><div class="table-head"><h2>Recent orders</h2><button class="outline small" data-jump="orders">View orders →</button></div>${orderTable(r.orders.slice(0,6))}</section>`}
function channels(){let r=state.report;if(!r)return '';return `${warningBar()}${cards()}<section class="panel panel-spaced"><div class="panel-head"><div><h2>Channel performance</h2><p>Sales, gross profit and known-cost contribution side by side</p></div></div>${r.channels.length?`<div class="table-wrap"><table><thead><tr><th>Channel</th><th>Sales type</th><th class="right">Net sales</th><th class="right">Gross profit</th><th class="right">Contribution</th><th class="right">Complete lines</th></tr></thead><tbody>${r.channels.map(ch=>`<tr><td>${chip(ch.channel)}</td><td>${ch.channel==='Faire'?'Wholesale':'Retail'}</td><td class="right">${money(ch.revenue,r.currency)}</td><td class="right">${formatProfit(ch.gross_profit,ch.cogs_lines>0)}</td><td class="right">${formatProfit(ch.profit,ch.complete>0)}</td><td class="right">${ch.complete}/${ch.lines}</td></tr>`).join('')}</tbody></table></div>`:empty('No channel sales','Connect a platform to see its contribution.')}</section>`}
function products(){let r=state.report;let costs=state.costs;return `${warningBar()}<section class="panel"><div class="table-head"><div><h2>Shopify COGS catalog</h2><p class="small-note">Synced from Shopify inventory item unit costs. SKUs match across every channel. Manually set a cost if Shopify leaves one blank.</p></div><span class="pill green">${costs.filter(c=>c.status==='available').length} priced SKUs</span></div><form id="costForm" class="form-row"><label>SKU<input id="costSku" placeholder="JLK001" required maxlength="150"></label><label>Unit COGS<input id="costAmount" type="number" min="0" step="0.000001" placeholder="12.50" required></label><label>Currency<input id="costCurrency" value="EUR" maxlength="3" required pattern="[a-zA-Z]{3}"></label><button class="primary" type="submit">Save override</button></form><p class="small-note">Updated costs apply to newly synced orders. Existing orders retain their original cost snapshot.</p>${costs.length?`<div class="table-wrap" style="margin-top:18px"><table><thead><tr><th>SKU</th><th>Product</th><th class="right">Unit cost</th><th>Status</th><th>Source</th></tr></thead><tbody>${costs.map(c=>`<tr><td class="sku">${esc(c.sku)}</td><td>${esc(c.product||'—')}</td><td class="right">${c.amount===null?'—':money(c.amount,c.currency)}</td><td><span class="cost-status ${esc(c.status)}">${esc(c.status)}</span></td><td>${esc(c.source||'Shopify')}</td></tr>`).join('')}</tbody></table></div>`:empty('No product costs yet','Connect Shopify and sync to retrieve the COGS catalog automatically.')}</section><section class="panel panel-spaced"><div class="table-head"><h2>Profit by product</h2></div>${productTable(r?.products||[])}</section>`}
function orders(){let r=state.report;return `${warningBar()}<section class="panel"><div class="table-head"><h2>Orders from all channels</h2><button class="outline small" id="exportCsv">↓ Export all CSV</button></div><p class="small-note">Displaying the 350 most recent matched order lines in this view. Download CSV for the current database export.</p>${orderTable(r?.orders||[])}</section>`}
function connectionCard(name){let matched=state.connections.filter(c=>c.provider===name),supported=['Shopify','Etsy','Faire'].includes(name),configured=state.configured[name];let subtitle={Shopify:'Sales + automatic SKU-level COGS',Etsy:'Orders, receipts and transactions',Amazon:'SP-API access requires developer approval',Michaels:'Marketplace account integration pending',Faire:'Wholesale orders through brand API'}[name];return `<div class="connection-card"><div class="connection-top"><div class="provider-icon ${name.toLowerCase()}">${ICONS[name]}</div><div style="flex:1"><h3>${name}</h3><p>${subtitle}</p></div><span class="pill ${matched.length?'green':''}">${matched.length?'Connected':supported&&configured?'Available':'CSV mode'}</span></div><p class="connection-note">${name==='Shopify'?'Product unit costs are read from Shopify inventory. Requires permission to view product costs.':name==='Faire'?'For brands, not Faire retailer purchasing accounts. The order amount mapping needs confirmation.':name==='Amazon'?'Connect through normalized CSV while public Selling Partner API approval is pending.':name==='Michaels'?'Export your seller orders and upload them through the common CSV format.':'Connect securely using Etsy OAuth. Financial fees remain incomplete until imported.'}</p>${matched.map(c=>`<div class="message ${c.error?'warning':'success'}"><strong>${esc(c.name)}</strong>${c.error?`<br>${esc(c.error)}`:`<br>${c.last_sync?'Last synced: '+esc(new Date(c.last_sync).toLocaleString()):'Connected · not yet synced'}`}</div><div class="connection-foot"><button class="outline small" data-sync="${c.id}">↻ Sync</button><button class="text-button" data-disconnect="${c.id}">Disconnect</button></div>`).join('')}${name==='Shopify'&&configured?`<form class="inline-form" id="shopForm"><input id="shopDomain" placeholder="your-store.myshopify.com" aria-label="Myshopify domain" required><button class="primary" type="submit">Connect Shopify →</button></form>`:supported&&configured?`<button class="primary" data-connect="${name.toLowerCase()}">Connect ${name} →</button>`:supported?`<div class="message warning">${name} OAuth needs application credentials configured by the operator. CSV imports work meanwhile.</div>`:''}</div>`}
function connectionsView(){return `<div class="banner"><span class="banner-icon">ⓘ</span><div><strong>Connect once, sync anytime.</strong> Shopify, Etsy and Faire require developer credentials and platform approval. Amazon and Michaels currently use CSV imports. No marketplace passwords are collected in this app.</div></div><div class="connections-grid">${PROVIDERS.map(connectionCard).join('')}</div><section class="panel panel-spaced"><div class="table-head"><h2>Import a marketplace export</h2><a href="/api/import/template" class="outline small">↓ CSV template</a></div><p class="small-note">Upload normalized line items from any of the five channels. Costs are matched to Shopify SKUs. Keep <b>fees</b> and <b>shipping_cost</b> blank if unknown; zero means an actual zero. CSV rows with a matching order ID are reconciled when an API connection later syncs that order.</p><form id="importForm" class="file-drop"><strong>Drop in your sales CSV</strong><p class="small-note">Up to 10,000 rows · 5 MB · UTF-8</p><input id="csvFile" type="file" accept=".csv,text/csv" required><button type="submit" class="primary" style="margin-top:15px">Import orders →</button></form></section>`}
function settingsView(){let s=state.fx||{fx:{},currency:'EUR'};let fx=s.fx||{};return `<div class="settings-list"><section class="panel"><div class="panel-head"><div><h2>Reporting currency</h2><p>Your preferred currency for combined sales reports.</p></div></div><form id="currencyForm" class="settings-row"><label>Base currency</label><select id="baseCurrency">${['EUR','USD','GBP','CAD','AUD','CHF','JPY'].map(c=>`<option ${s.currency===c?'selected':''}>${c}</option>`).join('')}</select><small>Changing the base currency requires matching FX rates for every source currency.</small><div><button type="submit" class="primary">Save currency</button></div></form></section><section class="panel"><div class="panel-head"><div><h2>Exchange rates</h2><p>How much one unit of a source currency is worth in your base currency.</p></div></div><form id="fxForm" class="settings-row"><label>1 source currency = amount in ${esc(s.currency)}</label><div class="fx-row"><input id="fxCode" maxlength="3" pattern="[A-Za-z]{3}" placeholder="USD" required style="max-width:92px"><input id="fxValue" type="number" min="0.00000001" step="any" placeholder="0.85" required><button class="primary" type="submit">Add rate</button></div></form><div class="fx-list">${Object.entries(fx).map(([c,r])=>`<div class="settings-row"><label>1 ${esc(c)} = ${number(r)} ${esc(s.currency)}</label></div>`).join('')||'<p class="small-note">No manual exchange rates saved yet.</p>'}</div><p class="small-note">Rates are manual reference rates, not historical daily exchange rates. Orders without a valid rate are excluded and flagged rather than combined incorrectly.</p></section><section class="panel"><h2>Data & privacy</h2><p class="small-note">Connected OAuth tokens are encrypted on the backend. Account data is isolated by workspace. Disconnecting a platform stops syncing but preserves previous orders in reports. Export a copy of your current records below.</p><a class="outline small" href="/api/export">↓ Export order data</a></section></div>`}
function render(){const v=state.view;$('view').innerHTML= v==='overview'?overview():v==='channels'?channels():v==='products'?products():v==='orders'?orders():v==='connections'?connectionsView():settingsView();bindView()}
function bindView(){document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>navigate(b.dataset.jump));
 const cost=$('costForm');if(cost)cost.onsubmit=async e=>{e.preventDefault();try{await api('/api/costs/'+encodeURIComponent($('costSku').value),{method:'PUT',body:JSON.stringify({sku:$('costSku').value,amount:$('costAmount').value,currency:$('costCurrency').value})});await loadCosts();render();toast('Product cost saved. Future synced orders will use this snapshot.')}catch(err){toast(err.message,true)}};
 const exportButton=$('exportCsv');if(exportButton)exportButton.onclick=()=>window.location.href='/api/export';
 const shop=$('shopForm');if(shop)shop.onsubmit=e=>{e.preventDefault();window.location.assign('/api/connect/shopify/start?shop='+encodeURIComponent($('shopDomain').value))};
 document.querySelectorAll('[data-connect]').forEach(b=>b.onclick=()=>window.location.assign('/api/connect/'+b.dataset.connect+'/start'));
 document.querySelectorAll('[data-sync]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{let r=await api('/api/connections/'+b.dataset.sync+'/sync',{method:'POST'});await Promise.all([loadConnections(),loadCosts(),loadReport()]);render();toast('Synced '+r.synced+' order lines, '+r.costs+' product costs.')}catch(err){await loadConnections();render();toast(err.message,true)}});
 document.querySelectorAll('[data-disconnect]').forEach(b=>b.onclick=async()=>{if(!confirm('Disconnect this store? Imported order history will be kept.'))return;try{await api('/api/connections/'+b.dataset.disconnect+'/disconnect',{method:'POST'});await loadConnections();render();toast('Store disconnected. History preserved.')}catch(err){toast(err.message,true)}});
 const imp=$('importForm');if(imp)imp.onsubmit=async e=>{e.preventDefault();let file=$('csvFile').files?.[0];if(!file)return;let fd=new FormData();fd.append('file',file);const btn=imp.querySelector('button');btn.disabled=true;try{let r=await api('/api/import',{method:'POST',body:fd});await loadReport();render();toast('Imported or updated '+r.imported+' order lines.')}catch(err){toast(err.message,true)}finally{btn.disabled=false}};
 const cf=$('currencyForm');if(cf)cf.onsubmit=async e=>{e.preventDefault();try{await api('/api/settings/currency',{method:'PUT',body:JSON.stringify({currency:$('baseCurrency').value})});state.user.currency=$('baseCurrency').value;await loadSettings();await loadReport();render();toast('Reporting currency updated.')}catch(err){toast(err.message,true)}};
 const fx=$('fxForm');if(fx)fx.onsubmit=async e=>{e.preventDefault();try{await api('/api/settings/fx',{method:'PUT',body:JSON.stringify({currency:$('fxCode').value,rate:$('fxValue').value})});await loadSettings();await loadReport();render();toast('Exchange rate saved.')}catch(err){toast(err.message,true)}};
}
boot();
